---
openapi: 3.0.1
info:
  title: API V1
  version: v1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  "/api/v1/auth/signup":
    post:
      summary: Sign up user and return JWT
      tags:
      - Auth
      parameters: []
      responses:
        '201':
          description: signup success
        '422':
          description: signup failure
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      format: email
                    password:
                      type: string
                    password_confirmation:
                      type: string
                  required:
                  - email
                  - password
                  - password_confirmation
              required:
              - user
  "/api/v1/auth/login":
    post:
      summary: Login user and return JWT
      tags:
      - Auth
      parameters: []
      responses:
        '200':
          description: login success
        '401':
          description: login failure
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      format: email
                    password:
                      type: string
                  required:
                  - email
                  - password
              required:
              - user
  "/api/v1/auth/logout":
    delete:
      summary: Logout user
      tags:
      - Auth
      security:
      - bearerAuth: []
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
        required: false
      responses:
        '204':
          description: logout success
        '401':
          description: logout with invalid token
  "/api/v1/coupons":
    get:
      summary: List active coupons
      tags:
      - Coupons
      security:
      - bearerAuth: []
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
        required: false
      - name: q
        in: query
        schema:
          type: string
        required: false
      - name: category
        in: query
        schema:
          type: string
        required: false
      responses:
        '200':
          description: query filtered
        '401':
          description: unauthorized
  "/api/v1/coupons/{slug}":
    parameters:
    - name: slug
      in: path
      required: true
      schema:
        type: string
    get:
      summary: Show active coupon detail
      tags:
      - Coupons
      security:
      - bearerAuth: []
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
        required: false
      responses:
        '200':
          description: coupon fetched
        '404':
          description: not found for inactive coupon
        '401':
          description: unauthorized
  "/api/v1/me":
    get:
      summary: Get current user
      tags:
      - Users
      security:
      - bearerAuth: []
      responses:
        '200':
          description: current user fetched
        '401':
          description: unauthorized
servers:
- url: http://localhost:3001
